modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved, DragN0007"
issueTrackerURL="https://discord.gg/jubppqCzXj"
[[mods]]
modId="deadlydinospt"
version="${1.18.2-1.0}"
displayName="Deadly Dinos: Park Tycoon"
logoFile="ddpt_logo.png"
#credits="" #optional
authors="DragN0007"
description='''
A park builder spin-off of DragN's Deadly Dinos!

Our Mod(s) Server & Issues Forum: https://discord.gg/jubppqCzXj
'''
[[dependencies.deadlydinospt]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.deadlydinospt]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19.0)"
ordering="NONE"
side="BOTH"
[[dependencies.deadlydinospt]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.57,)"
ordering="NONE"
side="BOTH"
